<?php

namespace App\Models;

use App\Core\Model;

class Permission extends Model
{

    protected ?int $id;
    protected ?int $user_id;
    protected ?string $permission;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(?int $user_id): void
    {
        $this->user_id = $user_id;
    }

    public function getPermission(): ?string
    {
        return $this->permission;
    }

    public function setPermission(?string $permission): void
    {
        $this->permission = $permission;
    }

    public static function getTableName(): string
    {
        return 'permissions'; // TODO: Change the autogenerated stub
    }
}