<?php

namespace App\Models;

use App\Core\Model;
class Profilepic extends Model
{
    protected ?int $id;
    protected ?int $user_id;
    protected ?string $picture;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(?int $user_id): void
    {
        $this->user_id = $user_id;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): void
    {
        $this->picture = $picture;
    }


    public static function getTableName(): string
    {
        return 'profilepic'; // TODO: Change the autogenerated stub
    }
}