<?php

namespace App\Models;

use App\Core\Model;

class User extends Model
{
    protected ?int $id;
    protected ?string $username = null;
    protected ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): void
    {
        $this->username = $username;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): void
    {
        $this->password = $password;
    }

    public static function getTableName(): string
    {
        return 'users'; // TODO: Change the autogenerated stub
    }
}